### ISSUE TITLE
想问如果想换个天气网站爬，怎么做呢，有建议吗

### ISSUE THREAD

**Issue by eveyw** [Vincedream/NodeMail#13]
首先感谢大神分享这个脚本！！！因为想获取外国的天气，但是墨迹没有，所以在想能不能换个天气网站爬虫。请问您之前有试过吗？谢谢！

**Comment by Vincedream** [comment]
当然可以 原理都是一样的  都是爬虫

**Comment by yhu-ctrl** [comment]
main.js的第36行WeatherUrl定义了天气网站的地址
然后在getWeatherData函数里把数据的获取方式改一哈就行了
😁
