### ISSUE TITLE
html的样式为什么只能嵌在行内？

### ISSUE THREAD

**Issue by beginnerJq** [Vincedream/NodeMail#17]
放在style或link的方式引入无效

**Comment by Vincedream** [comment]
嗯呢 应该是转换的过程中没有引入css  你看看你引入的方式是否有错误

**Comment by beginnerJq** [comment]
style或者link的方式。在微信小程序中打开邮箱样式无效。最后我自己用inlinecss转换一下才可以。:flushed:
