### ISSUE TITLE
关于天气数据获取地址的问题

### ISSUE THREAD

**Issue by BlBana** [Vincedream/NodeMail#2]
建议可以把`local`变量改成`zhejiang/hangzhou`这样带有省份的变量，再进行URL的拼接
```node
const WeatherUrl = "https://tianqi.moji.com/weather/china/"
```
否则有的同学只修改了`local`变量会出现天气获取不到的情况，可以在README中注明一下 ~

**Comment by Vincedream** [comment]
感谢，已经修正！
