### ISSUE TITLE
请问根目录下的 ecosyestem.json是干嘛用的？

### ISSUE THREAD

**Issue by leeboya** [Vincedream/NodeMail#3]
请问根目录下的 ecosyestem.json是干嘛用的？没有在源码中看到有用到这个配置的地方呢

**Comment by Vincedream** [comment]
这是配置pm2的文件，你可以看我博客中有关pm2的文章，简单来说就是更方便部署管理你的node应用





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by leeboya** [comment]
好的，谢谢博主！撒花✿✿ヽ(°▽°)ノ✿
