### ISSUE TITLE
为什么运行脚本报这个错？

### ISSUE THREAD

**Issue by crf-aaron** [Vincedream/NodeMail#4]
![image](https://user-images.githubusercontent.com/25742678/53547111-23382e00-3b69-11e9-97c0-4c6aae00d460.png)

**Comment by Kian-404** [comment]
@crf-git 你是不是没有安装依赖 npm install

**Comment by crf-aaron** [comment]
装了
![image](https://user-images.githubusercontent.com/25742678/53548077-99d62b00-3b6b-11e9-81a3-31af75a22131.png)

**Comment by Kian-404** [comment]
你把你的node_modules目录删掉再重新装一遍，或者用cnpm install, 可以跑的鸭
![1a9a2a73-1d87-4b7a-b53b-ecaf8ce031e3](https://user-images.githubusercontent.com/22888433/53548761-46fd7300-3b6d-11e9-989c-4e59366ea2d8.png)

**Comment by crf-aaron** [comment]
![image](https://user-images.githubusercontent.com/25742678/53549180-824c7180-3b6e-11e9-8f05-6c75490d9693.png)
你好，还是不行。你执行了吗？它是在到达发送时间执行的过程中报的错

**Comment by crf-aaron** [comment]
我这次听了您的建议使用cnpm下载，没有了之前使用npm下载时的警告，也就是使用cnpm下载了之前使用npm没下下来的node-mail包。但是相应的错误TypeError从78行变成了99行，对应的是从获取天气提醒函数变成了获取天气预报函数

**Comment by Kian-404** [comment]
可能是没拿到res.text, 你console一下res，看看有没有text

**Comment by crf-aaron** [comment]
打印res是undefined。
![image](https://user-images.githubusercontent.com/25742678/53550480-b9705200-3b71-11e9-99eb-6c501529b92b.png)

**Comment by Kian-404** [comment]
你是不是改了local， 你看一下WeatherUrl后面拼接的参数，这个地方作者直接把省拼接到后面了

**Comment by crf-aaron** [comment]
是的，这个我注意到了，刚刚我去测了一下天气接口，发现是接口不通，可能是公司把墨迹给禁了，我现在用手机热点可以访问了，但是又有了新问题。。。
![image](https://user-images.githubusercontent.com/25742678/53551812-13264b80-3b75-11e9-89cf-ee901abac4b8.png)

**Comment by crf-aaron** [comment]
在聚合函数里无限循环了

**Comment by Vincedream** [comment]
@你好，实在抱歉，或许是因为 [issue]( https://github.com/Vincedream/NodeMail/issues/2 ) 这个问题,如果还是不行，请您加我微信：vince_hua

**Comment by crf-aaron** [comment]
特此感谢以上二位的耐心指导！
作者的程序没有问题， 我这里出现的问题也已经完美解决了，再次感谢！
有出现相同问题的同学欢迎随时交流~

**Comment by jw0903** [comment]
@crf-git 遇到了同样的问题，看着好像是请求没成功，没有返回数据
