### ISSUE TITLE
怎么部署云服务

### ISSUE THREAD

**Issue by haiya07** [Vincedream/NodeMail#5]
请问要怎么部署到云服务器？谢谢

**Comment by Vincedream** [comment]
请查看我的博客，里面有服务器相关的博客，希望能帮到你 [vince's blog](https://vince.xin)

**Comment by haiya07** [comment]
非常感谢!发自我的华为手机-------- 原始邮件 --------主题：Re: [Vincedream/NodeMail] 怎么部署云服务 (#5)发件人：Vince 收件人：Vincedream/NodeMail 抄送：sam ,Author 请查看我的博客，里面有服务器相关的博客，希望能帮到你 vince's blog



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Vincedream/NodeMail","title":"Vincedream/NodeMail","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Vincedream/NodeMail"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Vincedream in #5: 请查看我的博客，里面有服务器相关的博客，希望能帮到你 [vince's blog](https://vince.xin)"}],"action":{"name":"View Issue","url":"https://github.com/Vincedream/NodeMail/issues/5#issuecomment-468605221"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Vincedream/NodeMail/issues/5#issuecomment-468605221",

"url": "https://github.com/Vincedream/NodeMail/issues/5#issuecomment-468605221",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by yzq007** [comment]
请问答主服务器连接失败怎么办
![image](https://user-images.githubusercontent.com/43276302/53722553-cad29a80-3ea0-11e9-963b-33345d2a6e01.png)

**Comment by Spike-Leung** [comment]
我是把项目放到服务器，然后下了个PM2， 用PM2启动你的脚本就可以了
