### ISSUE TITLE
这个 直接 会进行对方的垃圾箱啊，怎么绕过垃圾机制

### ISSUE THREAD

**Issue by xjf348060793** [Vincedream/NodeMail#6]
RT

**Comment by Vincedream** [comment]
内容不能是几个字，要正常的邮件内容，丰富一点就好





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)
