### ISSUE TITLE
兄弟你密码暴露了

### ISSUE THREAD

**Issue by zkl2333** [Vincedream/NodeMail#8]
https://github.com/Vincedream/NodeMail/blob/0a3e0444c5c023c5ed4e929092c568496dd1b608/demo/nodeMailDemo/app.js#L9

**Comment by Vincedream** [comment]
哈哈  改过来啦

**Comment by zkl2333** [comment]
> 哈哈 改过来啦

commit记录还会有 还是改密码靠谱
